[tool.poetry]
name = "embeddings"
version = "0.1.0"
description = ""
authors = ["dooreelko <github.63bjv@simplelogin.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
